import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/context";
import {UsageInitializer} from "@/components"


const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "PromptAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AppContextProvider>
          <UsageInitializer />
          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
